### ISSUE TITLE
1.1.3 Requirement List

### ISSUE THREAD

**Issue by chococtea** [ICT2101-P3Team2/ICT2101_P3-2#9]
Come up with functional & non-functional requirements and post inside the google doc (ICT2101_Project)
https://docs.google.com/document/d/1XFdPDBnVtw4iGJHG2eWd7-VvjRx0cah2YoD-MH4rWQo/edit?usp=sharing

**Comment by chococtea** [comment]
Finalised the requirements after the client's meeting. Can be found in the google docs

**Comment by EllynnTeo** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-4e238707-7fff-7133-9103-dc965e741082"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Functional Requirements:</span></p><div dir="ltr" style="margin-left:0pt;" align="left">

Role | Function
-- | --
Manager | Manager shall be able to view staff workload on landing pageManager shall be able to view staff availability on landing pageManager shall be able to allocate jobs, a week at a timeManager shall be able to edit allocation of jobs, a week at a timeManager shall be able to view past job allocation records up to 6 months’ worth
Staff | Staff shall be able to view their weekly job assignments on landing pageStaff shall be able to see their overall workload for the month on landing pageStaff shall be able to add availability up to 5 weeks beforeStaff shall be able to edit availability up to 5 weeks beforeStaff shall be able to indicate job preferencesStaff shall be able to reject job assignment, warned to discussed with their manager before proceedingStaff shall be able to accept job assignment
IT Administrator | IT Administrator shall be able to add new staff/manager account into the systemIT Administrator shall be able to edit staff/manager account in the systemIT Administrator shall be able to delete staff/manager account in the systemIT Administrator shall be able to view all staff/manager in the system

</div></b>
</body>
</html>

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-5fb2c698-7fff-b6b1-3709-9c2b60a9b0d6"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Non-functional Requirements:</span></p><div dir="ltr" style="margin-left:0pt;" align="left">

Category | Functions
-- | --
Security | All accounts in this system shall not be using NRIC as login due to PDPAThe system shall only be accessible on-site/using the company’s own WIFIAll users shall login to be able to access the system
Scalability | The system shall be able to support all the staff using it at the same timeThe system shall respond to the user’s click within 3 seconds
Availability | The system shall be accessible to all the users at any time on-site
Reliability | The system shall be able to perform at least 95 percent without failureThe system loading time in between pages shall not exceed 5 seconds.

</div></b>
</body>
</html>
